name: PebbleLogin
version: '1.0.6'
main: me.pebbleprojects.pebbleloginbeta.PebbleLogin
api-version: 1.13
authors: [PebbleProjects]
description: An advanced login system for Bukkit server.
commands:
  pebblelogin:
    description: Main command for PebbleLogin
  register:
    description: Register command for PebbleLogin
  login:
    description: Login command for PebbleLogin